"""empty message

Revision ID: 8705036a0f15
Revises: 
Create Date: 2024-12-08 11:40:39.468688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8705036a0f15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ho_so_xet_tuyen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ho_ten', sa.String(length=50), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('sdt', sa.String(length=10), nullable=False),
    sa.Column('dia_chi', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('trang_thai', sa.Enum('CHOXETTUYEN', 'DATRUNGTUYEN', 'KHONGTRUNGTUYEN', name='trangthaihsxt'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sdt')
    )
    op.create_table('mon_hoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_mon_hoc', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_mon_hoc')
    )
    op.create_table('nam_hoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_nam_hoc', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_nam_hoc')
    )
    op.create_table('quy_dinh',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_quy_dinh', sa.String(length=50), nullable=False),
    sa.Column('gioi_han_duoi', sa.Integer(), nullable=True),
    sa.Column('gioi_han_tren', sa.Integer(), nullable=True),
    sa.Column('noi_dung', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('noi_dung'),
    sa.UniqueConstraint('ten_quy_dinh')
    )
    op.create_table('tai_khoan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=50), nullable=False),
    sa.Column('mat_khau', sa.String(length=100), nullable=False),
    sa.Column('anh_dai_dien', sa.String(length=100), nullable=True),
    sa.Column('loai_tai_khoan', sa.Enum('NGUOIQUANTRI', 'NHANVIEN', 'GIAOVIEN', 'HOCSINH', name='loaitaikhoan'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_dang_nhap')
    )
    op.create_table('giao_vien',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ho_ten', sa.String(length=50), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('sdt', sa.String(length=10), nullable=False),
    sa.Column('dia_chi', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('tai_khoan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sdt'),
    sa.UniqueConstraint('tai_khoan_id')
    )
    op.create_table('hoc_ky',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_hoc_ky', sa.Enum('HK1', 'HK2', name='loaihocky'), nullable=False),
    sa.Column('nam_hoc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nam_hoc_id'], ['nam_hoc.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_hoc_ky', 'nam_hoc_id', name='uq_tenhocky_namhoc')
    )
    op.create_table('hoc_sinh',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ho_so_xet_tuyen_id', sa.Integer(), nullable=True),
    sa.Column('ho_ten', sa.String(length=50), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('sdt', sa.String(length=10), nullable=False),
    sa.Column('dia_chi', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('tai_khoan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ho_so_xet_tuyen_id'], ['ho_so_xet_tuyen.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ho_so_xet_tuyen_id'),
    sa.UniqueConstraint('sdt'),
    sa.UniqueConstraint('tai_khoan_id')
    )
    op.create_table('khoi_lop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_khoi', sa.Enum('KHOI_10', 'KHOI_11', 'KHOI_12', name='loaikhoilop'), nullable=False),
    sa.Column('nam_hoc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nam_hoc_id'], ['nam_hoc.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_khoi', 'nam_hoc_id', name='uq_tenkhoi_namhoc')
    )
    op.create_table('nguoi_quan_tri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ho_ten', sa.String(length=50), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('sdt', sa.String(length=10), nullable=False),
    sa.Column('dia_chi', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('tai_khoan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sdt'),
    sa.UniqueConstraint('tai_khoan_id')
    )
    op.create_table('nhan_vien',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ho_ten', sa.String(length=50), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('sdt', sa.String(length=10), nullable=False),
    sa.Column('dia_chi', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('tai_khoan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sdt'),
    sa.UniqueConstraint('tai_khoan_id')
    )
    op.create_table('bao_cao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_bao_cao', sa.String(length=50), nullable=False),
    sa.Column('mon_hoc_id', sa.Integer(), nullable=False),
    sa.Column('hoc_ky_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_ky_id'], ['hoc_ky.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mon_hoc_id'], ['mon_hoc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mon_hoc_id', 'hoc_ky_id', name='uq_tenkhoi_namhoc')
    )
    op.create_table('chuong_trinh_hoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_chuong_trinh', sa.String(length=50), nullable=False),
    sa.Column('khoi_lop_id', sa.Integer(), nullable=False),
    sa.Column('mon_hoc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['khoi_lop_id'], ['khoi_lop.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mon_hoc_id'], ['mon_hoc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('khoi_lop_id', 'mon_hoc_id', name='uq_khoilop_monhoc')
    )
    op.create_table('lop_hoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_lop', sa.String(length=50), nullable=False),
    sa.Column('si_so', sa.Integer(), nullable=False),
    sa.Column('khoi_lop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['khoi_lop_id'], ['khoi_lop.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_lop', 'khoi_lop_id', name='uq_tenlop_khoilop')
    )
    op.create_table('bang_diem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_bang_diem', sa.String(length=50), nullable=False),
    sa.Column('hoan_thanh', sa.Boolean(), nullable=False),
    sa.Column('lop_hoc_id', sa.Integer(), nullable=False),
    sa.Column('chuong_trinh_hoc_id', sa.Integer(), nullable=False),
    sa.Column('hoc_ky_id', sa.Integer(), nullable=False),
    sa.Column('giao_vien_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chuong_trinh_hoc_id'], ['chuong_trinh_hoc.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['giao_vien_id'], ['giao_vien.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hoc_ky_id'], ['hoc_ky.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lop_hoc_id'], ['lop_hoc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lop_hoc_id', 'chuong_trinh_hoc_id', 'hoc_ky_id', name='uq_tenkhoi_namhoc_hocky')
    )
    op.create_table('chuyen_lop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('la_doi_lop', sa.Boolean(), nullable=False),
    sa.Column('ngay_chuyen', sa.Date(), nullable=False),
    sa.Column('lop_hoc_id', sa.Integer(), nullable=False),
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['hoc_sinh.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lop_hoc_id'], ['lop_hoc.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hoc_sinh_id', 'lop_hoc_id', 'ngay_chuyen', name='uq_hocsinh_lophoc_ngaychuyen')
    )
    op.create_table('thong_ke',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_luong_dat', sa.Integer(), nullable=False),
    sa.Column('ti_le', sa.Float(), nullable=False),
    sa.Column('lop_hoc_id', sa.Integer(), nullable=False),
    sa.Column('bao_cao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bao_cao_id'], ['bao_cao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lop_hoc_id'], ['lop_hoc.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lop_hoc_id', 'bao_cao_id', name='uq_lophoc_baocao')
    )
    op.create_table('diem15p',
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_diem', sa.Float(), nullable=True),
    sa.Column('ten_cot', sa.String(length=50), nullable=False),
    sa.Column('bang_diem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bang_diem_id'], ['bang_diem.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['hoc_sinh.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diem1_tiet',
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_diem', sa.Float(), nullable=True),
    sa.Column('ten_cot', sa.String(length=50), nullable=False),
    sa.Column('bang_diem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bang_diem_id'], ['bang_diem.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['hoc_sinh.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diem_tbhk1',
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_diem', sa.Float(), nullable=True),
    sa.Column('ten_cot', sa.String(length=50), nullable=False),
    sa.Column('bang_diem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bang_diem_id'], ['bang_diem.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['hoc_sinh.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diem_tbhk2',
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_diem', sa.Float(), nullable=True),
    sa.Column('ten_cot', sa.String(length=50), nullable=False),
    sa.Column('bang_diem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bang_diem_id'], ['bang_diem.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['hoc_sinh.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diem_thi',
    sa.Column('hoc_sinh_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_diem', sa.Float(), nullable=True),
    sa.Column('ten_cot', sa.String(length=50), nullable=False),
    sa.Column('bang_diem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bang_diem_id'], ['bang_diem.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hoc_sinh_id'], ['hoc_sinh.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diem_thi')
    op.drop_table('diem_tbhk2')
    op.drop_table('diem_tbhk1')
    op.drop_table('diem1_tiet')
    op.drop_table('diem15p')
    op.drop_table('thong_ke')
    op.drop_table('chuyen_lop')
    op.drop_table('bang_diem')
    op.drop_table('lop_hoc')
    op.drop_table('chuong_trinh_hoc')
    op.drop_table('bao_cao')
    op.drop_table('nhan_vien')
    op.drop_table('nguoi_quan_tri')
    op.drop_table('khoi_lop')
    op.drop_table('hoc_sinh')
    op.drop_table('hoc_ky')
    op.drop_table('giao_vien')
    op.drop_table('tai_khoan')
    op.drop_table('quy_dinh')
    op.drop_table('nam_hoc')
    op.drop_table('mon_hoc')
    op.drop_table('ho_so_xet_tuyen')
    # ### end Alembic commands ###
